DO $$ BEGIN
  CREATE TYPE "WageType" AS ENUM ('MONTHLY', 'YEARLY');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "ComponentType" AS ENUM ('FIXED', 'PERCENT_OF_WAGE', 'PERCENT_OF_BASIC');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE "LeaveRequest"
  ADD COLUMN IF NOT EXISTS "allocationDays" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "attachmentUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "adminComment" TEXT;

UPDATE "LeaveRequest"
SET "allocationDays" = GREATEST(1, ("endDate"::date - "startDate"::date) + 1);

ALTER TABLE "SalaryStructure"
  ADD COLUMN IF NOT EXISTS "wageType" "WageType" NOT NULL DEFAULT 'MONTHLY',
  ADD COLUMN IF NOT EXISTS "fixedWage" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "pfEmployeePercent" DOUBLE PRECISION NOT NULL DEFAULT 12,
  ADD COLUMN IF NOT EXISTS "pfEmployerPercent" DOUBLE PRECISION NOT NULL DEFAULT 12,
  ADD COLUMN IF NOT EXISTS "professionalTax" DOUBLE PRECISION NOT NULL DEFAULT 200;

UPDATE "SalaryStructure"
SET "fixedWage" = "annualCtc"::DOUBLE PRECISION
WHERE "fixedWage" = 0 AND "annualCtc" IS NOT NULL;

ALTER TABLE "SalaryStructure"
  ALTER COLUMN "annualCtc" DROP NOT NULL;

ALTER TABLE "SalaryComponent"
  ADD COLUMN IF NOT EXISTS "compType" "ComponentType" NOT NULL DEFAULT 'FIXED',
  ADD COLUMN IF NOT EXISTS "value" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "calculatedAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;

UPDATE "SalaryComponent"
SET
  "value" = "amount"::DOUBLE PRECISION,
  "calculatedAmount" = "amount"::DOUBLE PRECISION
WHERE "value" = 0 AND "amount" IS NOT NULL;

ALTER TABLE "SalaryComponent"
  ALTER COLUMN "amount" DROP NOT NULL;
